spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
    username: sa
    password:
    # Database connection과 관련된 설정이 완료 됨
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # 자동으로 table을 만들어 줌
      ddl-auto: create
    properties:
      hibernate:
        # System.out에 출력(운영 환경에서는 사용 지양)
#        show_sql: true
        format_sql: true

# hibernate가 생성하는 sql이 debug시 모두 보임(System.out이 아닌 logger에 찍힘)
logging:
  level:
    org.hibernate.SQL: debug
    # binding parameter value를 로그에 표시해 줌
    org.hibernate.type: trace